# os: osx
language: python
python:
  - "3.6.1"
install:
  - pip install pip -U  
  - pip install -r requirements.txt
script: 
  - bash bin/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: hhhhhh
  - COMMIT_AUTHOR_EMAIL: "laszewski@gmail.com"